### ISSUE TITLE
Conflict with a Gravity Form Signature Field

### ISSUE THREAD

**Issue by maxproway** [Destiny-Elements/destiny-elements-pub#12]
Hi, when destiny-elements plugin is active the Gravity Form Signature Field does not work (field label is present but signature area is not visible).  Doesn't work in both cases - by adding form thru shortcode and thru destiny-elements element.
After plugin deactivation everything works.
I will be very appreciate  if you could fix this plugins conflict asap, since a signature field is critical for the website. 

Thank you, 
below our plugins versions:

Breakdance: 1.3.1
Gravity Forms 2.7.8
Destiny Elements: 1.5.1

**Comment by artur-burkalo** [comment]
This is going to be released shortly.

**Comment by maxproway** [comment]
Awesome, thank you so much for the so fast fix!
