### ISSUE TITLE
FAQPage indexing error from Google if mutliple text accordions on the same page

### ISSUE THREAD

**Issue by lockedm** [Destiny-Elements/destiny-elements-pub#6]
If multiple text accordions are on the same page, each with the FAQ schema on, multiple FAQPage fields will be added to the page. Google appears to not want to index pages with multiple FAQPage fields. 
![image](https://user-images.githubusercontent.com/112517932/219437133-bb7bc304-b2f4-4b07-bdd7-30b2166fc680.png)

And my page: https://spicedpearhealth.co.uk/faqs/

Can you detect if multiple elements are on the page and only place one FAQPage field? Thanks.

**Comment by artur-burkalo** [comment]
Thanks for the bug report, this can be done by adding all of them to the same schema, I'll add it for the next update.
